# Generated by Django 3.2.7 on 2021-11-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('_name', models.CharField(max_length=50)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('study_level', models.CharField(choices=[('1st', 'FirstYear'), ('2nd', 'SecondYear')], default='1st', max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='ChildPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.child')),
            ],
            options={
                'db_table': 'Child_Place',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('_name', models.CharField(max_length=50)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('childPlaces', models.ManyToManyField(through='toy.ChildPlace', to='toy.Child')),
            ],
        ),
        migrations.AddField(
            model_name='childplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.place'),
        ),
        migrations.AddField(
            model_name='child',
            name='id_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy.parent'),
        ),
    ]
